### PR TITLE
Created the card

### PR DESCRIPTION
**Pull request by Nabil-Elbir**
@97Fakhreddine @ALAAMEKKI hey guys, can you check the card that I've made and give me feedback ?

### CODE REVIEW

**Comment by 97Fakhreddine** [comment]
@Nabil-Elbir  Basically, the last commit looks way better than the previous. So, good job, that looks fine, and keep it up.

**Comment by Nabil-Elbir** [comment]
Thanks @97Fakhreddine 😄

**Comment by ALAAMEKKI** [comment]
Looks good, good job, I'm okay with that.

**Comment by Nabil-Elbir** [comment]
Thanks @ALAAMEKKI 😄

**Pull request merged**
